spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/demo?replicaSet=rs0&authSource=admin&directConnection=true
  task:
    scheduling:
      pool:
        size: 10
jwt:
  expiration: 300000
